### ISSUE TITLE
[PE-D] Sequence of commands error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-3/tp#229]
After using listvendor, I cannot enter editvendor?

![image.png](https://raw.githubusercontent.com/justintanyf/ped/main/files/39ad9ab6-c641-45d5-968f-596339f8eaa8.png)

I'm sorry, I do not mean to be harsh. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: justintanyf/ped#11

**Comment by calvintanwj** [comment]
I also can't replicate this.
