### ISSUE TITLE
[PE-D] Suggestion: It was a design decision to make filtering for passport number case sensitive, however I would suggest making it case insensitive?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-3/tp#247]
I think there will never be a case in reality where two people have the same passport numbers but have different capitalization. Thus, in order to facilitate a more user-friendly and accommodating search, I believe making it case-insensitive would be an improvement!

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: BryannYeap/ped#7

**Comment by calvintanwj** [comment]
Duplicate of #209
