### ISSUE TITLE
[PE-D] The image in the UG of the json file under the "Editing you data directly" section does not seem to accurately depict the actual json files.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-3/tp#257]
It might be due to an updated image, but the image in the UG shows guests being saved as `"persons"`, as well as having `"Archive"` in the same file. But in reality, guests are saved as `"guests"`, and also in a separate json file from archived guests, which are also named `"guests"`.

![image.png](https://raw.githubusercontent.com/BryannYeap/ped/main/files/93ef1a08-60dc-4a8a-b307-1f5b09ca88e1.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: BryannYeap/ped#10

**Comment by bingcheng45** [comment]
Added pull request to fix this issue.
