### ISSUE TITLE
Update UG for v1.1

### ISSUE THREAD

**Issue by calvintanwj** [AY2122S1-CS2103T-W12-3/tp#5]
Ensure that UG details are correct and move it into the repo

- [x] Table of contents
- [x] Quick start
- [x] Features
- [x] Add command
- [x] Edit command
- [x] Delete command
- [x] List command
- [x] View command
- [x] Save data
- [x] Edit data directly
- [x] Exit command
- [x] Archive data
- [x] Command summary
- [x] Param constraints
- [x] Glossary
- [x] FAQ

**Comment by NicolasCwy** [comment]
Can refer to PR #21, #27, #29,
